// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vrScraper.DB;

#nullable disable

namespace vrScraper.DB.Migrations
{
    [DbContext(typeof(VrScraperContext))]
    [Migration("20260323232659_AddTitleNormalization")]
    partial class AddTitleNormalization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("vrScraper.DB.Models.DbPlaybackEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Speed")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UtcTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlaybackEvents");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbScrapeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicatesSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Errors")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewVideos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PagesScraped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScrapeLogs");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbStar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbVideoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AddedUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataVp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disliked")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVr")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Liked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LocalRating")
                        .HasColumnType("REAL");

                    b.Property<string>("NormalizedTitle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ParsedDetails")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("PlayDurationEst")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("SiteRating")
                        .HasColumnType("REAL");

                    b.Property<string>("SiteVideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uploader")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ErrorCount");

                    b.HasIndex("Liked");

                    b.HasIndex("ParsedDetails");

                    b.HasIndex("Site", "SiteVideoId")
                        .IsUnique();

                    b.ToTable("VideoItems");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbVideoStar", b =>
                {
                    b.Property<long>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StarId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("INTEGER");

                    b.HasKey("VideoId", "StarId");

                    b.HasIndex("StarId");

                    b.ToTable("VideoStars");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbVideoTag", b =>
                {
                    b.Property<long>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("INTEGER");

                    b.HasKey("VideoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("VideoTags");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbVrTab", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActressBlacklist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActressWhitelist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagBlacklist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagWhitelist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoBlacklist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoWhitelist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Active");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbVideoStar", b =>
                {
                    b.HasOne("vrScraper.DB.Models.DbStar", "Star")
                        .WithMany("VideoStars")
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vrScraper.DB.Models.DbVideoItem", "Video")
                        .WithMany("VideoStars")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Star");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbVideoTag", b =>
                {
                    b.HasOne("vrScraper.DB.Models.DbTag", "Tag")
                        .WithMany("VideoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vrScraper.DB.Models.DbVideoItem", "Video")
                        .WithMany("VideoTags")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbStar", b =>
                {
                    b.Navigation("VideoStars");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbTag", b =>
                {
                    b.Navigation("VideoTags");
                });

            modelBuilder.Entity("vrScraper.DB.Models.DbVideoItem", b =>
                {
                    b.Navigation("VideoStars");

                    b.Navigation("VideoTags");
                });
#pragma warning restore 612, 618
        }
    }
}
